csk/urls.py
from django.urls import path
from csk.views import *
app_name="cskteam"
urlpatterns=[

    path('msd/',msd,name='msd'),
]

project7/urls.py
from django.contrib import admin
from django.urls import path,include
import rcb,csk

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rcb/',include('rcb.urls')),
    path('csk/',include('csk.urls')),
]

rcb/urls.py
from django.urls import path
from rcb.views import *
app_name="rcbteam"
urlpatterns=[

    path('virat/',virat,name='virat'),
]

csk/models.py
from django.db import models

# Create your models here.

rcb/models.py
from django.db import models

# Create your models here.

csk/views.py
from django.shortcuts import render

# Create your views here.

def msd(request):
    return render(request,'msd.html')

rcb/views.py
from django.shortcuts import render


# Create your views here.

def virat(request):
    return render(request,'virat.html')

templates/msd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center><h1>Msd:
        When you are expected to be strong and looked at as a strong individual people forget to ask how are you doing....
    </h1></center>
    <center><a href="{% url 'rcbteam:virat' %}"><h1>VIRAT RESPONSE</h1></a></center>
</body>
</html>

templates/virat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center><h1>Virat:
        MS Dhoni’s words hit home for me because I have always been looked at as someone who is very confident, mentally very strong, who can endure any circumstances and find a way and show us the way,
    </h1></center>
    <center><a href="{% url 'cskteam:msd' %}"><h1>MSD RESPONSE</h1></a></center>
</body>
</html>